language: node_js

node_js:
 - "0.10"

branches:
  only:
    - develop
    - master

services:
 - rabbitmq
 - mongodb

install:
 - sudo rabbitmq-plugins enable rabbitmq_mqtt
 - npm install

before_install:
 - npm install -g grunt-cli
